[os] 
NAME = "Amazon Linux"
VERSION = "2023"
ID = "amzn"
ID_LIKE = "fedora"
VERSION_ID = "2023"
PLATFORM_ID = "platform:al2023"
PRETTY_NAME = "Amazon Linux 2023"
ANSI_COLOR = "0;33"
CPE_NAME = "cpe:2.3:o:amazon:amazon_linux:2023"
HOME_URL = "https://aws.amazon.com/linux/"
BUG_REPORT_URL = "https://github.com/amazonlinux/amazon-linux-2023"
SUPPORT_END = "2028-03-01"

[applications]
    [applications.docker]
    version = "24.0.5, build ced0996"
    [applications.docker-compose]
    version = "Docker Compose version v2.22.0"